server:
  port: 9090

spring:
  application:
    name: SpringBoot

  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
